# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  #evaluation_interval default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    # Prometheus metrics at 9090
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'cineast'

    # Cineast instance at 4569
    static_configs:
      - targets: ['host.docker.internal:4569']

  - job_name: 'netdata-scrape'

    metrics_path: '/api/v1/allmetrics'
    params:
      # format: prometheus | prometheus_all_hosts
      format: [prometheus]
      #
      # sources: as-collected | raw | average | sum | volume
      # default is: average
      #source: [average]
      #
      # server name for this prometheus - the default is the client IP
      # for netdata to uniquely identify it
      #server: ['prometheus1']
    honor_labels: true


    static_configs:
      - targets: ['host.docker.internal:19999']

  - job_name: 'docker'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['docker.for.mac.host.internal:9323']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - ['docker.for.mac.host.internal:8080']