# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master, dev, vbs, lsc ]
  pull_request:
    branches: [ master, dev, vbs, lsc ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.6
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      # https://github.com/actions/cache/blob/main/examples.md#java---gradle
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
      # ADAMpro Protobuf are legacy at this point so they will never change
    - name: Cache ADAMpro Protobuf
      id: cache-protobuf
      uses: actions/cache@v2
      with:
        path: cineast-core/build/generated/main
        key: ${{ runner.os }}-adampro
    - name: Generate Proto
      run: ./gradlew cineast-core:generateProto
    - name: Test with Gradle
      run: ./gradlew test
    - name: runtime-jar
      run: ./gradlew cineast-runtime:fatJar
    - name: api-jar
      run: ./gradlew cineast-api:fatJar
